"""answers log

Revision ID: 0d3d9a584411
Revises: 8ff7a53319db
Create Date: 2026-09-29 11:20:24.081544
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d3d9a584411"
down_revision: str | None = "8ff7a53319db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("given_answer", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("answers_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_answers_log_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_answers_log_word_id"), ["word_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answers_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answers_log_word_id"))
        batch_op.drop_index(batch_op.f("ix_answers_log_user_id"))

    op.drop_table("answers_log")
    # ### end Alembic commands ###
