"""known words

Revision ID: 30f4fb37c333
Revises: 573ebd490932
Create Date: 2026-09-29 16:29:12.397456
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "30f4fb37c333"
down_revision: str | None = "573ebd490932"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_known_words",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "word_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_known_words")
    # ### end Alembic commands ###
