"""dictionaries words active

Revision ID: a4c7f83b13f9
Revises: 6788bce3d3c7
Create Date: 2026-09-29 00:09:37.888395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a4c7f83b13f9"
down_revision: str | None = "6788bce3d3c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_active_dictionaries",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dictionary_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dictionary_id"], ["dictionaries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "dictionary_id"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dictionary_id", sa.Integer(), nullable=False),
        sa.Column("article", sa.String(length=4), nullable=True),
        sa.Column("greek", sa.String(length=120), nullable=False),
        sa.Column("transcription", sa.String(length=160), nullable=False),
        sa.Column("translations_ru", sa.JSON(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=16), nullable=True),
        sa.Column("example_gr", sa.Text(), nullable=True),
        sa.Column("example_ru", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=255), nullable=True),
        sa.Column("image_source", sa.String(length=16), nullable=True),
        sa.Column("image_emoji", sa.String(length=16), nullable=True),
        sa.Column("audio_path", sa.String(length=255), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["dictionary_id"], ["dictionaries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_words_dictionary_id"), ["dictionary_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_words_dictionary_id"))

    op.drop_table("words")
    op.drop_table("user_active_dictionaries")
    op.drop_table("dictionaries")
    # ### end Alembic commands ###
