"""dialogues

Revision ID: 11f460a4be36
Revises: 30f4fb37c333
Create Date: 2026-10-01 23:25:57.014174
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "11f460a4be36"
down_revision: str | None = "30f4fb37c333"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dialogues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("speakers", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dialogue_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dialogue_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.Integer(), nullable=False),
        sa.Column("greek", sa.Text(), nullable=False),
        sa.Column("transcription", sa.Text(), nullable=False),
        sa.Column("translation_ru", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["dialogue_id"], ["dialogues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dialogue_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dialogue_lines_dialogue_id"), ["dialogue_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dialogue_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dialogue_lines_dialogue_id"))

    op.drop_table("dialogue_lines")
    op.drop_table("dialogues")
    # ### end Alembic commands ###
