"""draft word categories

Revision ID: 573ebd490932
Revises: cf02636c2510
Create Date: 2026-09-29 16:12:32.180920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "573ebd490932"
down_revision: str | None = "cf02636c2510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("category_suggestion", sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column("category_source", sa.String(length=16), nullable=True))
        batch_op.create_foreign_key(
            "fk_draft_words_category_id", "categories", ["category_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_draft_words_category_id", type_="foreignkey")
        batch_op.drop_column("category_source")
        batch_op.drop_column("category_suggestion")
        batch_op.drop_column("category_id")

    # ### end Alembic commands ###
