"""categories

Revision ID: cf02636c2510
Revises: 1291220c60cb
Create Date: 2026-09-29 15:51:38.905602
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf02636c2510"
down_revision: str | None = "1291220c60cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Expression index isn't picked up by autogenerate on SQLite; added by hand.
    op.create_index("ux_categories_name_lower", "categories", [sa.text("lower(name)")], unique=True)
    op.create_table(
        "user_active_categories",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "category_id"),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_words_category_id"), ["category_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_words_category_id", "categories", ["category_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_words_category_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_words_category_id"))
        batch_op.drop_column("category_id")

    op.drop_table("user_active_categories")
    op.drop_index("ux_categories_name_lower", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
