"""russian audio

Revision ID: 1291220c60cb
Revises: 0d3d9a584411
Create Date: 2026-09-29 12:18:58.779164
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1291220c60cb"
down_revision: str | None = "0d3d9a584411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("audio_ru_path", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("audio_ru_path")

    # ### end Alembic commands ###
