"""import jobs and draft words

Revision ID: ce4f353ea1ec
Revises: a4c7f83b13f9
Create Date: 2026-09-29 10:47:45.255802
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ce4f353ea1ec"
down_revision: str | None = "a4c7f83b13f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("has_source_pdf", sa.Boolean(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("selected_pages", sa.JSON(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("dictionary_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dictionary_id"], ["dictionaries.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_draft_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("include", sa.Boolean(), nullable=False),
        sa.Column("article", sa.String(length=4), nullable=True),
        sa.Column("greek", sa.String(length=120), nullable=False),
        sa.Column("transcription", sa.String(length=160), nullable=False),
        sa.Column("translations_ru", sa.JSON(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=16), nullable=True),
        sa.Column("example_gr", sa.Text(), nullable=True),
        sa.Column("example_ru", sa.Text(), nullable=True),
        sa.Column("image_emoji", sa.String(length=16), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("image_file", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["import_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_draft_words_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_draft_words_job_id"))

    op.drop_table("import_draft_words")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
