"""user settings

Revision ID: 8ff7a53319db
Revises: fccc30772901
Create Date: 2026-09-29 11:15:20.107565
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ff7a53319db"
down_revision: str | None = "fccc30772901"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    # ### end Alembic commands ###
