"""word image credit and query

Revision ID: fccc30772901
Revises: ce4f353ea1ec
Create Date: 2026-09-29 11:06:49.560232
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fccc30772901"
down_revision: str | None = "ce4f353ea1ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_query", sa.String(length=80), nullable=True))

    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_credit", sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column("image_query", sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_column("image_query")
        batch_op.drop_column("image_credit")

    with op.batch_alter_table("import_draft_words", schema=None) as batch_op:
        batch_op.drop_column("image_query")

    # ### end Alembic commands ###
